### PR TITLE
add ESIP and NDSR presentations to homepage

### PR DESCRIPTION
**Pull request by flyingzumwalt**
need to tidy up the layout to look nice, but wanted to add these links while I had them on my mind

### CODE REVIEW

**Comment by dcwalk** [comment]
This addresses #15 and #17 and attempts to address #16

**Comment by dcwalk** [comment]
@b5 or @flyingzumwalt can you review? I'm not super great at css stuff but tested for mobile and I think this is an improvement

**Review by b5 — APPROVED** [review]
LGTM

**Comment by dcwalk** [comment]
Okay! I'm merging in :) hopefully by end of sprint we'll have the deploy workflow down 💃

**Pull request merged**
