### PR TITLE
New theme - rebased

### PR DESCRIPTION
**Pull request by lightandluck**
This should supersede #70.
I took the liberty of branching off of that and rebasing onto master because on one of our last calls, that's what @b5 said needed to be done before it could be worked on.

I then
- Fixed the menu
- Added a quick media page because it was missing
- Formatted posts and pages (especially blogs) so they looked reasonable

Hopefully, this can get the website updated to a good spot!

### CODE REVIEW

**Review by b5 — APPROVED** [review]
@lightandluck just pulled your branch & had a look. LOOKS GREAT!

LET'S GET THIS MERGED!

**Comment by Frijol** [comment]
This looks SO GOOD and I'm SO EXCITED!

**Review by Frijol — APPROVED** [review]

**Comment by Frijol** [comment]
Should not block merge, but we should list authorship on the blog posts

**Comment by Frijol** [comment]
Throwing in some before/after screen shots just for the record

Before:

Screen Shot 2019-11-27 at 10 45 48 AM

Screen Shot 2019-11-27 at 10 41 41 AM
Screen Shot 2019-11-27 at 10 45 39 AM


After:
Screen Shot 2019-11-27 at 10 45 59 AM
Screen Shot 2019-11-27 at 10 45 24 AM
Screen Shot 2019-11-27 at 10 42 07 AM
Screen Shot 2019-11-27 at 10 45 20 AM

**Comment by lightandluck** [comment]
Thanks, All!!

@Frijol Thanks for catching the missing authors line and adding the screenshots 👍 Updated the new template to include authors. Also, remembered to make a couple links into buttons.

It's goin' in 🚀

**Comment by Frijol** [comment]
Yay! Deploy failed, though: https://circleci.com/gh/datatogether/website

**Comment by lightandluck** [comment]
@Frijol Thanks! Issue is outlined at #87 and just created a PR #88 to address it. Please take a look!

**Pull request merged**
