### PR TITLE
Create Jenkinsfile

### PR DESCRIPTION
**Pull request by victorb**

### CODE REVIEW

**Comment by victorb** [comment]
As I don't have write access to this repository, Jenkins won't be triggered on this PR (not contributor + changes to Jenkinsfile is a security precaution). Adding me with Write access or merging this PR will make Jenkins build it.

Secondly, you'll need to add the GitHub user `ImmutableJenkins` to have `write/push` access to this repository to be able to set the status of a PR/commit. What we do in the rest of the organizations is to have a `ci` team with `ImmutableJenkins` in, then every repository has that team with write access added to it.

**Review by b5 — APPROVED** [review]
THANK YOU VICTOR! Hopefully you have write access to this repo now, if so, please merge this!

**Comment by victorb** [comment]
@b5 hm, no, it's not working. Neither me or @ImmutableJenkins has write access to this repository.

**Comment by victorb** [comment]
@b5 sorry, ignore that, I missed to accept the invitation :face_with_head_bandage:

**Comment by victorb** [comment]
@b5 we still need to add @immutablejenkins to have write access to this repository to be able to set the status checks in PRs

**Comment by b5** [comment]
ah ok, just added @ImmutableJenkins, and made both you @lgierth admins on this repo. Thanks so much Victor!

**Pull request merged**
